# Generated by Django 2.2.11 on 2020-04-13 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('words_in_body', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='author.Author')),
            ],
            options={
                'ordering': ['-rating', 'genre', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votedby', to=settings.AUTH_USER_MODEL)),
                ('votedon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votedon', to='work.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work.Work')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
