# Generated by Django 2.2.11 on 2020-04-13 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolname', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('rating', models.FloatField(default=2.5)),
                ('photo', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('ranking', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('subscribed_author', models.ManyToManyField(related_name='_author_subscribed_author_+', to='author.Author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('sitename', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloglinks', to='author.Author')),
            ],
        ),
    ]
