# Generated by Django 2.2.11 on 2020-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200413_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='subscribed_author',
            field=models.ManyToManyField(related_name='subscribers_authors', to='author.Author'),
        ),
    ]
