# Generated by Django 2.2.11 on 2020-04-14 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200414_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='subscribed_author',
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
